# Generated by Django 5.2.7 on 2025-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteLine',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='番号')),
                ('type', models.IntegerField(verbose_name='タイプ')),
                ('output_type', models.IntegerField(verbose_name='出力タイプ')),
                ('is_available', models.IntegerField(verbose_name='利用可能フラグ')),
                ('available_user', models.IntegerField(verbose_name='利用可能ユーザー区分')),
                ('line', models.TextField(verbose_name='実行内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'exeute_line',
            },
        ),
    ]
