# Generated by Django 5.2.7 on 2025-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executeline',
            options={'ordering': ['-create_date'], 'verbose_name': '実行ライン', 'verbose_name_plural': '実行ライン'},
        ),
        migrations.AlterField(
            model_name='executeline',
            name='available_user',
            field=models.IntegerField(choices=[(1, '管理者'), (2, 'ユーザー'), (3, '公開')], default=2, verbose_name='利用可能ユーザー区分'),
        ),
        migrations.AlterField(
            model_name='executeline',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='利用可能フラグ'),
        ),
        migrations.AlterField(
            model_name='executeline',
            name='output_type',
            field=models.IntegerField(choices=[(1, '出力のみ'), (2, '実行のみ'), (3, '出力と実行')], default=1, verbose_name='出力タイプ'),
        ),
        migrations.AlterField(
            model_name='executeline',
            name='type',
            field=models.IntegerField(choices=[(1, 'マクロ'), (2, 'SQL'), (3, '正規表現')], default=1, verbose_name='タイプ'),
        ),
        migrations.AlterModelTable(
            name='executeline',
            table='execute_line',
        ),
    ]
